# Generated by Django 3.0.7 on 2020-07-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32, null=True)),
                ('img', models.ImageField(null=True, upload_to='img')),
                ('jianjie', models.CharField(max_length=32, null=True)),
                ('qq', models.CharField(max_length=32, null=True)),
                ('youxiang', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
