# Generated by Django 3.0.7 on 2020-07-15 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('jianjie', models.CharField(max_length=32)),
                ('price', models.CharField(max_length=32)),
                ('img', models.ImageField(null=True, upload_to='.')),
                ('data', models.DateTimeField(auto_now=True)),
                ('pd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.User')),
            ],
        ),
        migrations.CreateModel(
            name='texe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('jianjie', models.CharField(max_length=32)),
                ('price', models.CharField(max_length=32)),
                ('img', models.ImageField(null=True, upload_to='.')),
                ('data', models.DateTimeField(auto_now=True)),
                ('pd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.User')),
            ],
        ),
        migrations.CreateModel(
            name='sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.CharField(max_length=32)),
                ('lianxi', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('data', models.DateTimeField(auto_now=True)),
                ('pd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.User')),
            ],
        ),
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.CharField(max_length=32)),
                ('lianxi', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('data', models.DateTimeField(auto_now=True)),
                ('pd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.User')),
            ],
        ),
    ]
