# Generated by Django 3.0.7 on 2020-10-07 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_buy_sell_texe_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='to_chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32)),
                ('answer', models.CharField(max_length=32)),
                ('data', models.DateTimeField(auto_now=True)),
                ('neirong', models.CharField(max_length=32)),
                ('pd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.User')),
            ],
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32)),
                ('answer', models.CharField(max_length=32)),
                ('img', models.ImageField(null=True, upload_to='.')),
                ('pd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.User')),
            ],
        ),
    ]
