# Generated by Django 2.2.5 on 2021-04-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ggooo',
            fields=[
                ('iq', models.AutoField(primary_key=True, serialize=False)),
                ('公司', models.CharField(blank=True, max_length=255, null=True)),
                ('单位地址', models.CharField(blank=True, max_length=255, null=True)),
                ('行业性质', models.CharField(blank=True, max_length=255, null=True)),
                ('规模', models.CharField(blank=True, max_length=255, null=True)),
                ('性质', models.CharField(blank=True, max_length=255, null=True)),
                ('公司资产', models.CharField(blank=True, max_length=255, null=True)),
                ('职位名称', models.CharField(blank=True, max_length=7000, null=True)),
                ('职位详细', models.CharField(blank=True, max_length=7000, null=True)),
            ],
            options={
                'db_table': 'ggooo',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Too',
        ),
    ]
